name: Browser test

on: [push]

jobs:
  test:
    timeout-minutes: 15

    runs-on: ubuntu-20.04

    env:
      SELENIUM_IMAGE: selenium/standalone-chrome:4.0.0-alpha-7-prerelease-20200921

    steps:
      - name: Use Node 14
        uses: actions/setup-node@270253e841af726300e85d718a5f606959b2903c # v2.4.1
        with:
          node-version: 14

      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # https://github.com/actions/checkout/releases/tag/v2.3.4

      - name: Retrieve cached dependencies
        uses: actions/cache@5ca27f25cb3a0babe750cad7e4fddd3e55f29e9a # https://github.com/actions/cache/releases/tag/v2.1.1
        with:
          # See https://dev.to/mpocock1/how-to-cache-nodemodules-in-github-actions-with-yarn-24eh
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: yarn

      - name: Build the zip package
        run: yarn prepare-zip

      - name: Pull Selenium image
        run: docker pull $SELENIUM_IMAGE

      - name: Starting Selenium in Docker
        run: |
          docker run --rm --net=host -v /dev/shm:/dev/shm $SELENIUM_IMAGE &

          DELAY=15
          echo "Waiting $DELAY seconds for the server to start"
          sleep $DELAY

      - name: Start a static HTTP server
        run: |
          unzip SpreadsheetViewer.zip -d SpreadsheetViewerZip
          cd SpreadsheetViewerZip
          python3 -m http.server 8080 &

      - name: Run tests
        run: |
          URLS="http://localhost:8080/examples/js/index.html http://localhost:8080/examples/react/dist/index.html http://localhost:8080/examples/vue/dist/index.html http://localhost:8080/examples/angular/dist/angular/index.html"
          export URLS
          yarn workspace @spreadsheet-viewer/quickstart-test run-test

      - name: Upload quickstart Screenshots
        uses: actions/upload-artifact@27bce4eee761b5bc643f46a8dfb41b430c8d05f6 # https://github.com/actions/upload-artifact/releases/tag/v2.2.0
        if: always() # Run this step even if any of the steps above fails
        with:
          path: test/quickstart-*.png
          name: Quickstart Screenshots
